version: '3.1'

services:
  api:
    build: .
    ports:
      - "3700:3700"
    volumes:
      - ./config.toml:/app/config.toml
    depends_on:
      - external

  external:
    build: ./external
    ports:
      - "5100:5100"
    volumes:
      - ./config.toml:/config.toml
